project_id = "jzirqfzzvlbxwfzndaer"

[functions.webhooks-rssapp]
verify_jwt = false

[functions.worker]
verify_jwt = false

[functions.admin-retry]
verify_jwt = false

[functions.db-cleanup]
verify_jwt = false

[functions.media-processor]
verify_jwt = false

[functions.media-cleanup]
verify_jwt = false

[functions.admin-actions]
verify_jwt = false

[functions.x-poster]
verify_jwt = false
